### ISSUE TITLE
Advicing against trait-defined instructions

### ISSUE THREAD

**Issue by LoZack19** [FrancescoLFM/chip-8-emulator#1]
I strongly advice against this pattern:

```rust
pub trait SimpleInstruction {
    fn execute(&self);
}
```

Defining an instruction as an object that implements execute is inconvenient and risky. Not knowing at compile time the size of your objects and working with `Box<dyn ...>` is a huge pain in the ass. I also don't see the need to prefer this implementation, to one with a struct. I understand the need to want to implement functions of different types, but you can do this with an enum implementing execute rather than with a trait, which is likely to be very inconvenient here.

```rust
enum Instruction {
    Jump(JumpInstruction),
    Arithmetic(ArithmeticInstruction),
    // ...
 }
 
 impl Instruction {
     fn execute(&self) {
        // ...
     }
 }
 
 struct JumpInstruction {
   code: u8,
   // ...
 }
 ```

**Comment by FrancescoLFM** [comment]
Thank you for submitting this issue.
I'm aware that it isn't the best way to defining instructions, but I didn't know how powerful the enums are in rust.
Currently working on this fix.

**Comment by FrancescoLFM** [comment]
I just committed an old-fashioned and elegant solution:
```rust
fn cls(_code: u16) {
    // ...
}

fn jmp(code: u16) {
    // ...
}

pub type Instruction = fn(u16);
```
I think it's after all the cleanest and straight-forward solution, perfect for the simple chip 8 instruction set.
